// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */

const sidebars = {
  allcontent: [
    //Tutorial Parent
    /*
    {
      type: "category",
      label: "Tutorials",
      link: {
        type: "doc",
        id: "tutorials/get-started",
      },
      collapsed: false,
      items: [
        // Build and Test Code
        {
          type: "category",
          label: "Build & Test Code",
          link: {
            type: "doc",
            id: "tutorials/build-code",
          },
          collapsed: true,
          items: [{ type: "autogenerated", dirName: "tutorials/build-code" }],
        },

        // Deploy Services
        {
          type: "category",
          label: "Deploy Services",
          link: {
            type: "doc",
            id: "tutorials/deploy-services",
          },
          collapsed: true,
          items: [
            { type: "autogenerated", dirName: "tutorials/deploy-services" },
          ],
        },

        // Manage Feature Flags - feature-flags
        {
          type: "category",
          label: "Manage Feature Flags",
          link: {
            type: "doc",
            id: "tutorials/manage-feature-flags",
          },
          collapsed: true,
          items: [
            {
              type: "autogenerated",
              dirName: "tutorials/manage-feature-flags",
            },
          ],
        },

        // Manage Cloud Costs - cloud-cost-management
        {
          type: "category",
          label: "Manage Cloud Costs",
          link: {
            type: "doc",
            id: "tutorials/manage-cloud-costs",
          },
          collapsed: true,
          items: [
            {
              type: "autogenerated",
              dirName: "tutorials/manage-cloud-costs",
            },
          ],
        },

        // Manage Service Reliability - service-reliability-management
        {
          type: "category",
          label: "Manage Service Reliability",
          link: {
            type: "doc",
            id: "tutorials/manage-service-reliability",
          },
          collapsed: true,
          items: [
            {
              type: "autogenerated",
              dirName: "tutorials/manage-service-reliability",
            },
          ],
        },

        // Orchestrate Security Tests - security-testing-orchestration
        {
          type: "category",
          label: "Orchestrate Security Tests",
          link: {
            type: "doc", // "generated-index",
            id: "tutorials/orchestrate-security-tests",
          },
          collapsed: true,
          items: [
            {
              type: "autogenerated",
              dirName: "tutorials/orchestrate-security-tests",
            },
          ],
        },

        // Run Chaos Experiments - chaos-engineering
        {
          type: "category",
          label: "Run Chaos Experiments",
          link: {
            type: "doc",
            id: "tutorials/run-chaos-experiments",
          },
          collapsed: true,
          items: [
            {
              type: "autogenerated",
              dirName: "tutorials/run-chaos-experiments",
            },
          ],
        },

        // Platform - platform
        {
          type: "category",
          label: "Administer Harness Platform",
          link: {
            type: "doc",
            id: "tutorials/platform",
          },
          collapsed: true,
          items: [{ type: "autogenerated", dirName: "tutorials/platform" }],
        },

        //Additional Items in this parent can go here.
      ],
    },
    */
    // Documentation Parent
    {
      type: "category",
      label: "Documentation",
      link: {
        type: "generated-index",
      },
      collapsed: true,
      items: [
        {
          type: "category",
          label: "Getting Started",
          link: {
            type: "generated-index",
            slug: "getting-started",
          },
          collapsed: true,
          items: [
            {
              type: "autogenerated",
              dirName: "getting-started",
            },
          ],
        },
        {
          /*
          type: "doc",
          label: "Continuous Integration",
          id: "continuous-integration",
          */
          type: "category",
          label: "Continuous Integration",
          link: {
            type: "generated-index",
            slug: "continuous-integration",
            /* Uncomment this block while we have a landing page for module docs
            type: "doc",
            id: "continuous-integration",
            */
          },
          collapsed: true,
          items: [
            {
              type: "autogenerated",
              dirName: "continuous-integration",
            },
          ],
        },
        {
          /*
          type: "doc",
          label: "Continuous Delivery",
          id: "continuous-delivery",
          */
          type: "category",
          label: "Continuous Delivery & GitOps",
          link: {
            type: "generated-index",
            slug: "/continuous-delivery",
            /* Uncomment this block while we have a landing page for module docs
            type: "doc",
            id: "continuous-delivery",
            */
          },
          collapsed: true,
          items: [
            {
              type: "autogenerated",
              dirName: "continuous-delivery",
            },
          ],
        },
        {
          /*
          type: "doc",
          label: "Feature Flags",
          id: "feature-flags",
          */
          type: "category",
          label: "Feature Flags",
          link: {
            type: "generated-index",
            slug: "/feature-flags",
            /* Uncomment this block while we have a landing page for module docs
            type: "doc",
            id: "feature-flags",
            */
          },
          collapsed: true,
          items: [
            {
              type: "autogenerated",
              dirName: "feature-flags",
            },
          ],
        },
        {
          /*
          type: "doc",
          label: "Cloud Cost Management",
          id: "cloud-cost-management",
          */
          type: "category",
          label: "Cloud Cost Management",
          link: {
            type: "generated-index",
            slug: "/cloud-cost-management",
            /* Uncomment this block while we have a landing page for module docs
            type: "doc",
            id: "cloud-cost-management",
            */
          },
          collapsed: true,
          items: [
            {
              type: "autogenerated",
              dirName: "cloud-cost-management",
            },
          ],
        },
        {
          /*
          type: "doc",
          label: "Service Reliability Management",
          id: "service-reliability-management",
          */
          type: "category",
          label: "Service Reliability Management",
          link: {
            type: "generated-index",
            slug: "/service-reliability-management",
            /* Uncomment this block while we have a landing page for module docs
            type: "doc",
            id: "security-testing-orchestration",
            */
          },
          collapsed: true,
          items: [
            {
              type: "autogenerated",
              dirName: "service-reliability-management",
            },
          ],
        },
        {
          /*
          type: "doc",
          label: "Security Testing Orchestration",
          id: "security-testing-orchestration",
          */
          type: "category",
          label: "Security Testing Orchestration",
          link: {
            type: "generated-index",
            slug: "/security-testing-orchestration",
            /* Uncomment this block while we have a landing page for module docs
            type: "doc",
            id: "security-testing-orchestration",
            */
          },
          collapsed: true,
          items: [
            {
              type: "autogenerated",
              dirName: "security-testing-orchestration",
            },
          ],
        },
        {
          /*
          type: "doc",
          label: "Chaos Engineering",
          id: "chaos-engineering",
          */
          type: "category",
          label: "Chaos Engineering",
          link: {
            type: "generated-index",
            slug: "/chaos-engineering",
            /* Uncomment this block while we have a landing page for module docs
            type: "doc",
            id: "chaos-engineering",
            */
          },
          collapsed: true,
          items: [
            {
              type: "autogenerated",
              dirName: "chaos-engineering",
            },
          ],
        },
        {
          /*
          type: "doc",
          label: "Harness Platform",
          id: "platform",
          */
          type: "category",
          label: "Harness Platform",
          link: {
            type: "generated-index",
            slug: "/platform",
            /* Uncomment this block while we have a landing page for module docs
            type: "doc",
            id: "platform",
            */
          },
          collapsed: true,
          items: [
            {
              type: "autogenerated",
              dirName: "platform",
            },
          ],
        },
        {
          /*
          type: "doc",
          label: "Self-Managed Enterprise Edition",
          id: "self-managed-enterprise-edition",
          */
          type: "category",
          label: "Self-Managed Enterprise Edition",
          link: {
            type: "generated-index",
            slug: "/self-managed-enterprise-edition",
            /* Uncomment this block while we have a landing page for module docs
            type: "doc",
            id: "self-managed-enterprise-edition",
            */
          },
          collapsed: true,
          items: [
            {
              type: "autogenerated",
              dirName: "self-managed-enterprise-edition",
            },
          ],
        },
        {
          /*
          type: "doc",
          label: "FirstGen docs",
          id: "first-gen",
          */
          type: "category",
          label: "Harness FirstGen",
          link: {
            type: "generated-index",
            slug: "/first-gen",
            /* Uncomment this block while we have a landing page for module docs
            type: "doc",
            id: "first-gen",
            */
          },
          collapsed: true,
          items: [
            {
              type: "autogenerated",
              dirName: "first-gen",
            },
          ],
        },
        {
          /*
          type: "doc",
          label: "FAQs",
          id: "frequently-asked-questions",
          */
          type: "category",
          label: "FAQs",
          link: {
            type: "generated-index",
            slug: "/frequently-asked-questions",
            /* Uncomment this block while we have a landing page for module docs
            type: "doc",
            id: "frequently-asked-questions",
            */
          },
          collapsed: true,
          items: [
            {
              type: "autogenerated",
              dirName: "frequently-asked-questions",
            },
          ],
        },
        {
          /*
          type: "doc",
          label: "Troubleshooting",
          id: "troubleshooting",
          */
          type: "category",
          label: "Troubleshooting",
          link: {
            type: "generated-index",
            slug: "/troubleshooting",
            /* Uncomment this block while we have a landing page for module docs
            type: "doc",
            id: "troubleshooting",
            */
          },
          collapsed: true,
          items: [
            {
              type: "autogenerated",
              dirName: "troubleshooting",
            },
          ],
        },
      ],
    },

    //Additional Items in this parent can go here.
  ],
};

module.exports = sidebars;
