// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */

const sidebars = {
  kb: [
    // KB Parent
    {
      type: "category",
      label: "KB",
      link: {
        type: "doc",
        id: "kb",
        //type: 'generated-index',
      },
      collapsed: false,
      items: [{ type: "autogenerated", dirName: "." }],
    },

    //Additional Items in this parent can go here.
  ],
};

module.exports = sidebars;
