// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */

const sidebars = {
  iacmbeta: [
    {
      /*
      type: "doc",
      label: "IaCM",
      id: "infrastructure-as-code",
      */
      type: "category",
      label: "Infrastructure as Code",
      link: {
        type: "generated-index",
        slug: "/infrastructure-as-code",
        /* Uncomment this block while we have a landing page for module docs
        type: "doc",
        id: "infrastructure-as-code",
        */
      },
      collapsed: true,
      items: [
        {
          type: "autogenerated",
          dirName: "infrastructure-as-code-management",
        },
      ],
    },

    //Additional Items in this parent can go here.
  ],
};

module.exports = sidebars;
