import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';
const sidebars: SidebarsConfig = {
  kb: [
    // KB Parent
    {
      type: 'category',
      label: 'Knowledge Base',
      className: 'sidebar-allkb',
      link: {
        type: 'doc',
        id: 'kb',
      },
      collapsed: false,
      items: [
        {
          /*
          type: "doc",
          label: "Security Testing Orchestration",
          id: "security-testing-orchestration",
          */
          // type: 'category',
          // label: 'Security Testing Orchestration',
          // className: 'sidebar-sto',
          // link: {
          //   type: 'generated-index',
          //   slug: '/security-testing-orchestration',
          // },
          // collapsed: true,
          // items: [
          //   {
          //     type: 'autogenerated',
          //     dirName: 'security-testing-orchestration',
          //   },
          // ],
        },
        /*
        {
          type: 'category',
          label: 'Armory',
          className: 'sidebar-armory',
          link: {
            type: 'generated-index',
            slug: '/armory',
          },
          collapsed: true,
          items: [
            {
              type: 'autogenerated',
              dirName: 'armory',
            },
          ],
        },
        */
        /*
     Reference Architecture Section
    */
        {
          type: 'link',
          label: 'Reference Architectures',
          className: 'sidebar-reference-arch',
          href: '/kb/reference-architectures/',
        },
      ],
    },
  ],
  ReferenceArchitectures: [
    {
      type: 'category',
      label: 'Reference Architectures',
      className: 'sidebar-reference-arch',
      link: {
        type: 'doc',
        id: 'reference-architectures',
      },
      collapsed: true,
      items: [
        {
          type: 'autogenerated',
          dirName: 'reference-architectures',
        },
      ],
    },
    // All KB
    {
      type: 'link',
      label: 'Show All Knowledge Base',
      className: 'sidebar-allkb',
      href: '/kb',
      customProps: {
        description: 'All KB.',
      },
    },
  ],
};

export default sidebars;
