import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';
const sidebars: SidebarsConfig = {
  kb: [
    // KB Parent
    {
      type: 'category',
      label: 'Knowledge Base',
      className: 'sidebar-allkb',
      link: {
        type: 'doc',
        id: 'kb',
      },
      collapsed: false,
      items: [
        {
          /*
          type: "doc",
          label: "Continuous Delivery",
          id: "continuous-delivery",
          */
          type: 'category',
          label: 'Continuous Delivery & GitOps',
          className: 'sidebar-cd',
          link: {
            type: 'generated-index',
            slug: '/continuous-delivery',
          },
          collapsed: true,
          items: [
            {
              type: 'autogenerated',
              dirName: 'continuous-delivery',
            },
          ],
        },
        {
          /*
          type: "doc",
          label: "Security Testing Orchestration",
          id: "security-testing-orchestration",
          */
          type: 'category',
          label: 'Security Testing Orchestration',
          className: 'sidebar-sto',
          link: {
            type: 'generated-index',
            slug: '/security-testing-orchestration',
          },
          collapsed: true,
          items: [
            {
              type: 'autogenerated',
              dirName: 'security-testing-orchestration',
            },
          ],
        },
        {
          /*
          type: "doc",
          label: "Internal Developer Portal",
          id: "idp",
          */
          type: 'category',
          label: 'Internal Developer Portal',
          className: 'sidebar-idp',
          link: {
            type: 'generated-index',
            slug: '/idp',
          },
          collapsed: true,
          items: [
            {
              type: 'autogenerated',
              dirName: 'internal-developer-portal',
            },
          ],
        },
        {
          /*
          type: "doc",
          label: "Continuous Error Tracking",
          id: "continuous-error-tracking",
          */
          type: 'category',
          label: 'Continuous Error Tracking',
          className: 'sidebar-cet',
          link: {
            type: 'generated-index',
            slug: '/continuous-error-tracking',
          },
          collapsed: true,
          items: [
            {
              type: 'autogenerated',
              dirName: 'continuous-error-tracking',
            },
          ],
        },
        {
          /*
          type: "doc",
          label: "Harness Platform",
          id: "platform",
          */
          type: 'category',
          label: 'Harness Platform',
          className: 'sidebar-platform',
          link: {
            type: 'generated-index',
            slug: '/platform',
          },
          collapsed: true,
          items: [
            {
              type: 'autogenerated',
              dirName: 'platform',
            },
          ],
        },
        {
          /*
          type: "doc",
          label: "Armory",
          id: "armory",
          */
          type: 'category',
          label: 'Armory',
          className: 'sidebar-armory',
          link: {
            type: 'generated-index',
            slug: '/armory',
          },
          collapsed: true,
          items: [
            {
              type: 'autogenerated',
              dirName: 'armory',
            },
          ],
        },
        /*
     Reference Architecture Section
    */
        {
          type: 'link',
          label: 'Reference Architectures',
          className: 'sidebar-reference-arch',
          href: '/kb/reference-architectures/',
        },
      ],
    },
  ],
  ReferenceArchitectures: [
    {
      type: 'category',
      label: 'Reference Architectures',
      className: 'sidebar-reference-arch',
      link: {
        type: 'doc',
        id: 'reference-architectures',
      },
      collapsed: true,
      items: [
        {
          type: 'autogenerated',
          dirName: 'reference-architectures',
        },
      ],
    },
    // All KB
    {
      type: 'link',
      label: 'Show All Knowledge Base',
      className: 'sidebar-allkb',
      href: '/kb',
      customProps: {
        description: 'All KB.',
      },
    },
  ],
};

export default sidebars;
