/**
 * When a DMS content doc is opened directly (e.g. from search or a link), redirect to the
 * parent page that loads it via DynamicMarkdownSelector, with the correct hash so the right
 * tab is selected.
 *
 * Uses a generated map (from scripts/generate-dms-redirect-map.mjs) of content path ->
 * { parentRepoPath, hash }. If the current path is in the map, redirect to canonical(parent) + #hash.
 * Otherwise falls back to convention: .../content/<section>/<slug> -> .../<section>#<hash from slug>.
 * Repo path vs URI: paths with leading "N-" in segments have a canonical URI with those stripped.
 */
import ExecutionEnvironment from '@docusaurus/ExecutionEnvironment';

// Generated by scripts/generate-dms-redirect-map.mjs (run at prebuild/build)
import dmsRedirectMap from './generated/dmsRedirectMap.js';
import { repoPathToCanonical } from './repoPathToCanonical.js';

/** Normalize like DMS: lowercase, remove spaces (for hash segment) */
function dmsNormalize(s) {
  return s.toLowerCase().replace(/\s+/g, '');
}

function slugToHash(slug) {
  // e.g. opentofu-quickstart -> opentofu, terraform-quickstart -> terraform
  const withoutQuickstart = slug.replace(/-quickstart$/i, '');
  return encodeURIComponent(dmsNormalize(withoutQuickstart));
}

function runRedirect() {
  if (!ExecutionEnvironment.canUseDOM) return;
  const pathname = window.location.pathname;

  const pathForLookup = pathname
    .replace(/^\/docs\//, '')
    .replace(/\/$/, '')
    .replace(/\.(md|mdx)$/i, '');
  const entry = dmsRedirectMap && dmsRedirectMap[pathForLookup];
  if (entry) {
    const parentFullPath = '/docs/' + entry.parentRepoPath;
    const canonical = repoPathToCanonical(parentFullPath) || parentFullPath;
    window.location.replace(`${canonical}#${entry.hash}`);
    return;
  }

  const contentMatch = pathname.match(/^(.*?)\/(content|supported-formats)\/(.+)$/);
  if (!contentMatch) return;

  const [, prefix, segmentType, rest] = contentMatch;
  const parts = rest.split('/').filter(Boolean);
  let section;
  let slug;
  if (segmentType === 'supported-formats') {
    // e.g. /docs/artifact-registry/supported-formats/docker-quickstart -> section=supported-formats, slug=docker-quickstart
    if (parts.length < 1) return;
    section = 'supported-formats';
    slug = parts[parts.length - 1];
  } else {
    // content: e.g. /docs/.../content/get-started/opentofu-quickstart -> section=get-started, slug=opentofu-quickstart
    if (parts.length < 2) return;
    section = parts[0];
    slug = parts[parts.length - 1];
  }
  const targetPage = `${prefix}/${section}`;
  const hash = slugToHash(slug);
  const redirectTo = `${targetPage}#${hash}`;
  window.location.replace(redirectTo);
}

if (ExecutionEnvironment.canUseDOM) {
  runRedirect();
}
